services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "5000:80"

  backend:
    container_name: backend
    build: 
      context: ./crud-api
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - sqlite_data:/var/www/html/data

volumes:
  sqlite_data: